import json
import os
from datetime import datetime

import requests
from flask import Flask, jsonify, request

try:
    import psycopg
except ImportError:
    psycopg = None

app = Flask(__name__)

BOT_TOKEN = os.environ.get("MAJD_TELEGRAM_BOT_TOKEN", "").strip()
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "").strip()
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-4.1-mini").strip()
WEBHOOK_URL = os.environ.get("MAJD_WEBHOOK_URL", "").rstrip("/")
WEBHOOK_SECRET = os.environ.get("MAJD_WEBHOOK_SECRET", "").strip()
ADMIN_API_KEY = os.environ.get("MAJD_ADMIN_API_KEY", "").strip()
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
DEMO_URL = os.environ.get("V6_DEMO_URL", "").strip()
OWNER_CONTACT = os.environ.get("OWNER_CONTACT", "").strip()

TELEGRAM_API = f"https://api.telegram.org/bot{BOT_TOKEN}" if BOT_TOKEN else ""
MAX_HISTORY = 12

SYSTEM_PROMPT = """أنت مجد، مساعد مبيعات محترف وودود لوكيل العملاء V6.
مهمتك فهم احتياج العميل وشرح المنتج وتحويل المهتم الجدي إلى صفقة، من دون ضغط أو ادعاءات كاذبة.

معلومات المنتج:
- وكيل مبيعات وخدمة عملاء يعمل حالياً على Telegram، مع نواة تكامل لـFacebook Messenger.
- يجيب بالعربية عن المنتجات والأسعار والتوصيل والدفع.
- يجمع بيانات الطلب، يعرض مراجعة كاملة، ولا يحفظ الطلب قبل تأكيد العميل.
- يحفظ الجلسات والطلبات في PostgreSQL، يمنع معالجة الرسائل المكررة، ويدعم Webhooks آمنة.
- توجد لوحة إدارة محمية، حالات للطلبات، سجل تغييرات، إحصاءات إيرادات، واختبارات آلية.
- قابل لتخصيص المنتجات والأسعار والألوان وطرق الدفع والتوصيل وهوية العميل.
- الاستضافة الحالية على Render والكود على GitHub.

قواعد البيع:
- السعر المستهدف يبدأ من 5,000 دولار أمريكي، وقد يزيد حسب التخصيص والتكامل والدعم.
- لا تمنح خصماً ولا تعد بسعر نهائي أقل من 5,000 دولار.
- لا تدّع وجود ميزة غير مذكورة. قل بوضوح إن أي قناة إضافية مثل WhatsApp تحتاج تكاملاً رسمياً منفصلاً.
- اسأل أسئلة قصيرة عن نشاط العميل، عدد الرسائل، القنوات، اللغات، والتكاملات المطلوبة.
- عندما يظهر اهتمام جدي اطلب الاسم، الشركة، البلد، البريد/الهاتف، والوقت المناسب للتواصل.
- أخبر العميل أنك مساعد ذكاء اصطناعي، ولا تنتحل شخصية المالك.
- لا تطلب كلمات مرور أو رموز تحقق أو بيانات بطاقات.
- لا تنفذ مدفوعات. أحِل الاتفاق النهائي والتوقيع والتحصيل إلى المالك.
- أجب بلغة العميل وباختصار، واجعل لكل رسالة هدفاً واحداً واضحاً.
"""

def init_db():
    if not DATABASE_URL or psycopg is None:
        return
    with psycopg.connect(DATABASE_URL) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS majd_sales_messages(
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                chat_id TEXT NOT NULL,
                username TEXT,
                role TEXT NOT NULL,
                content TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        """)
        conn.execute("""
            CREATE INDEX IF NOT EXISTS idx_majd_sales_messages_chat
            ON majd_sales_messages(chat_id, id DESC)
        """)

def save_message(chat_id, username, role, content):
    if not DATABASE_URL or psycopg is None:
        return
    with psycopg.connect(DATABASE_URL) as conn:
        conn.execute(
            """INSERT INTO majd_sales_messages(chat_id, username, role, content)
               VALUES(%s,%s,%s,%s)""",
            (str(chat_id), username, role, content),
        )

def load_history(chat_id):
    if not DATABASE_URL or psycopg is None:
        return []
    with psycopg.connect(DATABASE_URL) as conn:
        rows = conn.execute(
            """SELECT role, content FROM majd_sales_messages
               WHERE chat_id=%s ORDER BY id DESC LIMIT %s""",
            (str(chat_id), MAX_HISTORY),
        ).fetchall()
    return [{"role": r[0], "content": r[1]} for r in reversed(rows)]

def telegram_send(chat_id, text):
    response = requests.post(
        f"{TELEGRAM_API}/sendMessage",
        json={"chat_id": chat_id, "text": text[:4000]},
        timeout=20,
    )
    response.raise_for_status()

def ai_reply(chat_id, username, user_text):
    history = load_history(chat_id)
    context = SYSTEM_PROMPT
    if DEMO_URL:
        context += f"\nرابط الديمو المعتمد: {DEMO_URL}"
    if OWNER_CONTACT:
        context += f"\nوسيلة التواصل المعتمدة مع المالك: {OWNER_CONTACT}"

    input_messages = [{"role": "system", "content": context}]
    input_messages.extend(history)
    input_messages.append({"role": "user", "content": user_text})

    response = requests.post(
        "https://api.openai.com/v1/responses",
        headers={
            "Authorization": f"Bearer {OPENAI_API_KEY}",
            "Content-Type": "application/json",
        },
        json={
            "model": OPENAI_MODEL,
            "input": input_messages,
            "temperature": 0.4,
            "max_output_tokens": 500,
        },
        timeout=45,
    )
    response.raise_for_status()
    payload = response.json()
    text = payload.get("output_text", "").strip()
    if not text:
        for item in payload.get("output", []):
            for content in item.get("content", []):
                if content.get("type") == "output_text":
                    text += content.get("text", "")
    return text.strip() or "أعتذر، لم أتمكن من تجهيز الرد الآن. حاول بعد قليل."

@app.get("/")
@app.get("/health")
def health():
    missing = [
        name for name, value in {
            "MAJD_TELEGRAM_BOT_TOKEN": BOT_TOKEN,
            "OPENAI_API_KEY": OPENAI_API_KEY,
            "MAJD_WEBHOOK_URL": WEBHOOK_URL,
            "MAJD_WEBHOOK_SECRET": WEBHOOK_SECRET,
        }.items() if not value
    ]
    return jsonify({
        "service": "majd-v6-sales-bot",
        "status": "ok" if not missing else "configuration_required",
        "missing": missing,
        "time": datetime.utcnow().isoformat(timespec="seconds") + "Z",
    }), 200 if not missing else 503

@app.post("/majd/webhook")
def telegram_webhook():
    if WEBHOOK_SECRET:
        supplied = request.headers.get("X-Telegram-Bot-Api-Secret-Token", "")
        if supplied != WEBHOOK_SECRET:
            return jsonify({"error": "unauthorized"}), 401

    update = request.get_json(silent=True) or {}
    message = update.get("message") or {}
    text = str(message.get("text") or "").strip()
    chat_id = (message.get("chat") or {}).get("id")
    sender = message.get("from") or {}
    username = sender.get("username")

    if not chat_id or not text:
        return jsonify({"ok": True})

    if text.startswith("/start"):
        greeting = (
            "أهلاً بك، أنا مجد، مساعد مبيعات ذكي لوكيل العملاء V6. "
            "أستطيع شرح المنتج والديمو والتخصيص والسعر. ما نوع نشاطك؟"
        )
        save_message(chat_id, username, "assistant", greeting)
        telegram_send(chat_id, greeting)
        return jsonify({"ok": True})

    save_message(chat_id, username, "user", text)
    try:
        reply = ai_reply(chat_id, username, text)
        save_message(chat_id, username, "assistant", reply)
        telegram_send(chat_id, reply)
    except Exception:
        telegram_send(chat_id, "صار عطل مؤقت أثناء تجهيز الرد. حاول بعد قليل من فضلك.")
        return jsonify({"ok": False}), 500
    return jsonify({"ok": True})

@app.post("/admin/setup-webhook")
def setup_webhook():
    if not ADMIN_API_KEY or request.headers.get("X-Admin-Key") != ADMIN_API_KEY:
        return jsonify({"error": "unauthorized"}), 401
    target = f"{WEBHOOK_URL}/majd/webhook"
    response = requests.post(
        f"{TELEGRAM_API}/setWebhook",
        json={"url": target, "secret_token": WEBHOOK_SECRET},
        timeout=20,
    )
    return jsonify(response.json()), response.status_code

def configure_webhook():
    if not TELEGRAM_API or not WEBHOOK_URL or not WEBHOOK_SECRET:
        return
    response = requests.post(
        f"{TELEGRAM_API}/setWebhook",
        json={
            "url": f"{WEBHOOK_URL}/majd/webhook",
            "secret_token": WEBHOOK_SECRET,
            "drop_pending_updates": False,
        },
        timeout=20,
    )
    response.raise_for_status()


try:
    init_db()
    configure_webhook()
except Exception:
    pass
