import json
import os
from datetime import datetime

import requests
from flask import Flask, jsonify, request

try:
    import psycopg
except ImportError:
    psycopg = None

app = Flask(__name__)

BOT_TOKEN = os.environ.get("MAJD_TELEGRAM_BOT_TOKEN", "").strip()
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "").strip()
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-4.1-mini").strip()
WEBHOOK_URL = os.environ.get("MAJD_WEBHOOK_URL", "").rstrip("/")
WEBHOOK_SECRET = os.environ.get("MAJD_WEBHOOK_SECRET", "").strip()
ADMIN_API_KEY = os.environ.get("MAJD_ADMIN_API_KEY", "").strip()
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
DEMO_URL = os.environ.get("V6_DEMO_URL", "").strip()
OWNER_CONTACT = os.environ.get("OWNER_CONTACT", "").strip()
OWNER_CHAT_ID = os.environ.get("MAJD_OWNER_CHAT_ID", "").strip()

TELEGRAM_API = f"https://api.telegram.org/bot{BOT_TOKEN}" if BOT_TOKEN else ""
MAX_HISTORY = 12
PROCESSED_UPDATES = set()
SCRIPTED_STATES = {}

SYSTEM_PROMPT = """أنت مجد، مساعد مبيعات محترف وودود لوكيل العملاء V6.
مهمتك فهم احتياج العميل وشرح المنتج وتحويل المهتم الجدي إلى صفقة، من دون ضغط أو ادعاءات كاذبة.

معلومات المنتج:
- وكيل مبيعات وخدمة عملاء يعمل حالياً على Telegram، مع نواة تكامل لـFacebook Messenger.
- يجيب بالعربية عن المنتجات والأسعار والتوصيل والدفع.
- يجمع بيانات الطلب، يعرض مراجعة كاملة، ولا يحفظ الطلب قبل تأكيد العميل.
- يحفظ الجلسات والطلبات في PostgreSQL، يمنع معالجة الرسائل المكررة، ويدعم Webhooks آمنة.
- توجد لوحة إدارة محمية، حالات للطلبات، سجل تغييرات، إحصاءات إيرادات، واختبارات آلية.
- قابل لتخصيص المنتجات والأسعار والألوان وطرق الدفع والتوصيل وهوية العميل.
- الاستضافة الحالية على Render والكود على GitHub.

قواعد البيع:
- السعر المستهدف يبدأ من 5,000 دولار أمريكي، وقد يزيد حسب التخصيص والتكامل والدعم.
- لا تمنح خصماً ولا تعد بسعر نهائي أقل من 5,000 دولار.
- لا تدّع وجود ميزة غير مذكورة. قل بوضوح إن أي قناة إضافية مثل WhatsApp تحتاج تكاملاً رسمياً منفصلاً.
- اسأل أسئلة قصيرة عن نشاط العميل، عدد الرسائل، القنوات، اللغات، والتكاملات المطلوبة.
- عندما يظهر اهتمام جدي اطلب الاسم، الشركة، البلد، البريد/الهاتف، والوقت المناسب للتواصل.
- أخبر العميل أنك مساعد ذكاء اصطناعي، ولا تنتحل شخصية المالك.
- لا تطلب كلمات مرور أو رموز تحقق أو بيانات بطاقات.
- لا تنفذ مدفوعات. أحِل الاتفاق النهائي والتوقيع والتحصيل إلى المالك.
- أجب بلغة العميل وباختصار، واجعل لكل رسالة هدفاً واحداً واضحاً.
"""

def init_db():
    if not DATABASE_URL or psycopg is None:
        return
    with psycopg.connect(DATABASE_URL) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS majd_sales_messages(
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                chat_id TEXT NOT NULL,
                username TEXT,
                role TEXT NOT NULL,
                content TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        """)
        conn.execute("""
            CREATE INDEX IF NOT EXISTS idx_majd_sales_messages_chat
            ON majd_sales_messages(chat_id, id DESC)
        """)

def save_message(chat_id, username, role, content):
    if not DATABASE_URL or psycopg is None:
        return
    with psycopg.connect(DATABASE_URL) as conn:
        conn.execute(
            """INSERT INTO majd_sales_messages(chat_id, username, role, content)
               VALUES(%s,%s,%s,%s)""",
            (str(chat_id), username, role, content),
        )

def load_history(chat_id):
    if not DATABASE_URL or psycopg is None:
        return []
    with psycopg.connect(DATABASE_URL) as conn:
        rows = conn.execute(
            """SELECT role, content FROM majd_sales_messages
               WHERE chat_id=%s ORDER BY id DESC LIMIT %s""",
            (str(chat_id), MAX_HISTORY),
        ).fetchall()
    return [{"role": r[0], "content": r[1]} for r in reversed(rows)]

def telegram_send(chat_id, text):
    response = requests.post(
        f"{TELEGRAM_API}/sendMessage",
        json={"chat_id": chat_id, "text": text[:4000]},
        timeout=20,
    )
    response.raise_for_status()

def scripted_sales_reply(chat_id, user_text, username=None):
    text = str(user_text or "").strip()
    lowered = text.lower()
    state = SCRIPTED_STATES.setdefault(str(chat_id), {"last_topic": None, "lead": {}})

    phone_match = __import__("re").search(r"(?<!\\d)(\\+?\\d[\\d\\s-]{7,18}\\d)(?!\\d)", text)
    email_match = __import__("re").search(r"[\\w.+-]+@[\\w.-]+\\.[A-Za-z]{2,}", text)
    has_lead_details = bool(phone_match or email_match or (
        "اسمي" in lowered and any(word in lowered for word in ("شركة", "شركتي", "مؤسسة", "بلد"))
    ))
    if has_lead_details:
        state["lead"]["raw"] = text
        state["lead"]["username"] = username
        state["last_topic"] = "lead_captured"
        if OWNER_CHAT_ID and str(chat_id) != OWNER_CHAT_ID:
            try:
                telegram_send(
                    OWNER_CHAT_ID,
                    "🔔 عميل مهتم جديد بوكيل V6\n"
                    f"Telegram: @{username or 'بدون اسم مستخدم'}\n"
                    f"البيانات: {text}",
                )
            except Exception:
                pass
        return (
            "تم تسجيل بياناتك كعميل مهتم ✅\n"
            "سيراجع المالك طلبك ويتواصل معك لمشاركة الديمو ومناقشة التخصيص والسعر النهائي. "
            "قبل ذلك: كم تقريباً عدد رسائل العملاء التي تستقبلها يومياً؟"
        )

    affirmative = lowered in {"نعم", "اي", "إي", "ايوه", "أيوه", "تقريبا", "تقريباً", "ضروري", "مهم"}
    if affirmative and state.get("last_topic") == "whatsapp_required":
        state["last_topic"] = "business_type"
        return (
            "واضح، سنعتبر WhatsApp متطلباً أساسياً في العرض. يحتاج ربطاً رسمياً منفصلاً "
            "بحسب البلد ومزوّد الخدمة. ما نوع نشاطك، وكم رسالة عملاء تستقبل يومياً تقريباً؟"
        )
    if affirmative and state.get("last_topic") == "demo_lead":
        state["last_topic"] = "awaiting_lead"
        return "أرسل اسمك، اسم الشركة، البلد، ورقم الهاتف أو البريد وسأجهز طلب الديمو."

    if any(phrase in lowered for phrase in ("من الاول", "من الأول", "بلش من جديد", "ابدأ من جديد", "نبدأ من جديد")):
        SCRIPTED_STATES[str(chat_id)] = {"last_topic": "welcome", "lead": {}}
        return (
            "أهلاً بك من جديد. أنا مجد، مساعد مبيعات لوكيل العملاء V6. "
            "ما نوع نشاطك؟"
        )

    if lowered in {"مالك", "المالك"} or any(
        phrase in lowered for phrase in ("تواصل مع المالك", "احكي مع المالك", "حكي المالك")
    ):
        state["last_topic"] = "awaiting_lead"
        return (
            "لأوصلك بالمالك أرسل اسمك، اسم الشركة، البلد، "
            "ورقم الهاتف أو البريد، وسأرسل بياناتك له مباشرة."
        )

    if any(word in lowered for word in ("السعر", "بكم", "قديش", "كم حق", "التكلفة")):
        state["last_topic"] = "price"
        return (
            "سعر وكيل العملاء V6 يبدأ من 5,000 دولار أمريكي، "
            "وقد يزيد حسب القنوات والتخصيص والدعم المطلوب. "
            "ما القنوات التي تريد تشغيله عليها؟"
        )

    if any(word in lowered for word in ("ميزات", "مميزات", "شو بيعمل", "اشرح", "تفاصيل", "شو هو", "ماذا تقدمون")):
        state["last_topic"] = "features"
        return (
            "وكيل العملاء V6 يرد على أسئلة العملاء، يعرض المنتجات والأسعار والتوصيل، "
            "يجمع بيانات الطلب، ويطلب تأكيد العميل قبل الحفظ. لديه PostgreSQL، "
            "لوحة إدارة محمية، سجل لحالات الطلبات، Webhooks آمنة واختبارات آلية، "
            "ويمكن تخصيصه حسب نشاطك. ما نوع نشاطك؟"
        )

    if any(word in lowered for word in ("تخصيص", "خصص", "تفصيل", "حسب شغلي", "حسب نشاطي")):
        state["last_topic"] = "customization"
        business = state.get("lead", {}).get("business_type")
        prefix = f"لنشاط «{business}» " if business else ""
        return (
            f"يمكن تخصيص V6 {prefix}من حيث اسم وهوية الوكيل، المنتجات والأسعار، "
            "اللغات، أسئلة العملاء، جمع بيانات المهتمين، لوحة الإدارة والقنوات المطلوبة. "
            "اكتب أهم ثلاث مهام تريد من الوكيل تنفيذها."
        )

    if any(word in lowered for word in ("واتساب", "whatsapp")):
        state["last_topic"] = "whatsapp_required"
        return (
            "يمكن إضافة WhatsApp عبر تكامل رسمي منفصل حسب بلدك ومزوّد الخدمة. "
            "النسخة الحالية تعمل على Telegram، وتوجد نواة تكامل لـFacebook Messenger. "
            "هل WhatsApp شرط أساسي لمشروعك؟"
        )

    if any(word in lowered for word in ("ديمو", "تجربة", "جرب", "رابط", "اعرض لي")):
        if DEMO_URL:
            state["last_topic"] = "demo_sent"
            return f"تفضل رابط الديمو: {DEMO_URL}\nبعد التجربة أخبرني ما التخصيص المطلوب."
        state["last_topic"] = "demo_lead"
        return (
            "الديمو متاح. لإرسال الرابط المعتمد اكتب اسمك، اسم الشركة، البلد، "
            "ورقم الهاتف أو البريد المناسب للتواصل."
        )

    if any(word in lowered for word in ("اشتري", "مهتم", "اريد", "أريد", "تواصل", "اتفاق")):
        state["last_topic"] = "awaiting_lead"
        return (
            "ممتاز. لنجهز عرضاً مناسباً: أرسل اسمك، اسم الشركة، البلد، "
            "البريد أو الهاتف، والقنوات المطلوبة. الاتفاق النهائي والدفع يتمان مع المالك."
        )

    if any(word in lowered for word in ("مرحبا", "اهلا", "أهلا", "سلام", "hello", "hi")):
        state["last_topic"] = "welcome"
        return (
            "أهلاً بك. أنا مجد، مساعد مبيعات لوكيل العملاء V6. "
            "هل تريد معرفة الميزات، السعر، الديمو، أم خيارات التخصيص؟"
        )

    if state.get("last_topic") in {"welcome", "business_type"}:
        business = text
        state["lead"]["business_type"] = business
        state["last_topic"] = "business_type"
        return (
            f"ممتاز، يمكن تخصيص V6 لنشاط «{business}» ليجيب العملاء، "
            "يجمع بيانات المهتمين، يصنف الطلبات، ويحوّل الحالات الجدية للمالك. "
            "على أي قناة يتواصل عملاؤك حالياً: Telegram، WhatsApp، Facebook أم غيرها؟"
        )

    return (
        "فهمت. حتى أعطيك جواباً مناسباً، اختر ما تريد: "
        "الميزات، السعر، الديمو، التخصيص، أم التواصل مع المالك؟"
    )

def ai_reply(chat_id, username, user_text):
    if not OPENAI_API_KEY:
        return scripted_sales_reply(chat_id, user_text, username)

    history = load_history(chat_id)
    context = SYSTEM_PROMPT
    if DEMO_URL:
        context += f"\nرابط الديمو المعتمد: {DEMO_URL}"
    if OWNER_CONTACT:
        context += f"\nوسيلة التواصل المعتمدة مع المالك: {OWNER_CONTACT}"

    input_messages = [{"role": "system", "content": context}]
    input_messages.extend(history)
    input_messages.append({"role": "user", "content": user_text})

    response = requests.post(
        "https://api.openai.com/v1/responses",
        headers={
            "Authorization": f"Bearer {OPENAI_API_KEY}",
            "Content-Type": "application/json",
        },
        json={
            "model": OPENAI_MODEL,
            "input": input_messages,
            "temperature": 0.4,
            "max_output_tokens": 500,
        },
        timeout=45,
    )
    response.raise_for_status()
    payload = response.json()
    text = payload.get("output_text", "").strip()
    if not text:
        for item in payload.get("output", []):
            for content in item.get("content", []):
                if content.get("type") == "output_text":
                    text += content.get("text", "")
    return text.strip() or "أعتذر، لم أتمكن من تجهيز الرد الآن. حاول بعد قليل."

@app.get("/")
@app.get("/health")
def health():
    missing = [
        name for name, value in {
            "MAJD_TELEGRAM_BOT_TOKEN": BOT_TOKEN,
            "OPENAI_API_KEY": OPENAI_API_KEY,
            "MAJD_WEBHOOK_URL": WEBHOOK_URL,
            "MAJD_WEBHOOK_SECRET": WEBHOOK_SECRET,
        }.items() if not value
    ]
    return jsonify({
        "service": "majd-v6-sales-bot",
        "status": "ok" if not missing else "configuration_required",
        "missing": missing,
        "time": datetime.utcnow().isoformat(timespec="seconds") + "Z",
    }), 200 if not missing else 503

@app.post("/majd/webhook")
def telegram_webhook():
    if WEBHOOK_SECRET:
        supplied = request.headers.get("X-Telegram-Bot-Api-Secret-Token", "")
        if supplied != WEBHOOK_SECRET:
            return jsonify({"error": "unauthorized"}), 401

    update = request.get_json(silent=True) or {}
    update_id = update.get("update_id")
    if update_id is not None:
        if update_id in PROCESSED_UPDATES:
            return jsonify({"ok": True})
        PROCESSED_UPDATES.add(update_id)
        if len(PROCESSED_UPDATES) > 5000:
            for old_id in sorted(PROCESSED_UPDATES)[:1000]:
                PROCESSED_UPDATES.discard(old_id)

    message = update.get("message") or {}
    text = str(message.get("text") or "").strip()
    chat_id = (message.get("chat") or {}).get("id")
    sender = message.get("from") or {}
    username = sender.get("username")

    if not chat_id or not text:
        return jsonify({"ok": True})

    if text.startswith("/myid") or text.startswith("/register_owner"):
        telegram_send(
            chat_id,
            f"رقم حسابك الداخلي هو:\n{chat_id}\n"
            "أرسله لمجد داخل ChatGPT ليتم تسجيلك كمالك دائم.",
        )
        return jsonify({"ok": True})

    if text.startswith("/start"):
        SCRIPTED_STATES[str(chat_id)] = {"last_topic": "welcome", "lead": {}}
        greeting = (
            "أهلاً بك، أنا مجد، مساعد مبيعات ذكي لوكيل العملاء V6. "
            "أستطيع شرح المنتج والديمو والتخصيص والسعر. ما نوع نشاطك؟"
        )
        save_message(chat_id, username, "assistant", greeting)
        telegram_send(chat_id, greeting)
        return jsonify({"ok": True})

    save_message(chat_id, username, "user", text)
    try:
        reply = ai_reply(chat_id, username, text)
        save_message(chat_id, username, "assistant", reply)
        telegram_send(chat_id, reply)
    except Exception:
        telegram_send(chat_id, "صار عطل مؤقت أثناء تجهيز الرد. حاول بعد قليل من فضلك.")
        # Always acknowledge Telegram updates; a 500 makes Telegram resend the
        # same update and causes duplicate customer-facing error messages.
        return jsonify({"ok": True})
    return jsonify({"ok": True})

@app.post("/admin/setup-webhook")
def setup_webhook():
    if not ADMIN_API_KEY or request.headers.get("X-Admin-Key") != ADMIN_API_KEY:
        return jsonify({"error": "unauthorized"}), 401
    target = f"{WEBHOOK_URL}/majd/webhook"
    response = requests.post(
        f"{TELEGRAM_API}/setWebhook",
        json={"url": target, "secret_token": WEBHOOK_SECRET},
        timeout=20,
    )
    return jsonify(response.json()), response.status_code

def configure_webhook():
    if not TELEGRAM_API or not WEBHOOK_URL or not WEBHOOK_SECRET:
        return
    response = requests.post(
        f"{TELEGRAM_API}/setWebhook",
        json={
            "url": f"{WEBHOOK_URL}/majd/webhook",
            "secret_token": WEBHOOK_SECRET,
            "drop_pending_updates": False,
        },
        timeout=20,
    )
    response.raise_for_status()


try:
    init_db()
    configure_webhook()
except Exception:
    pass
