"""Reviewed answers and a private follow-up queue on the existing database."""

import json
import re
import unicodedata
from contextlib import closing
from datetime import datetime, timezone
from urllib.parse import urlsplit


def normalized_question(value):
    text = str(value).strip().lower()
    text = ''.join(c for c in text if not unicodedata.combining(c))
    for old, new in (("أ", "ا"), ("إ", "ا"), ("آ", "ا"), ("ة", "ه"), ("ى", "ي")):
        text = text.replace(old, new)
    return ' '.join(re.sub(r'[^\w\s]', ' ', text).split())


def validated_faq(payload):
    if not isinstance(payload, dict):
        raise ValueError("FAQ must be an object")
    item = {}
    for key, limit in {"question": 300, "answer": 2000, "source_title": 120}.items():
        value = payload.get(key)
        if not isinstance(value, str) or not value.strip() or len(value) > limit:
            raise ValueError(f"{key} is required; maximum {limit} characters")
        item[key] = value.strip()
    aliases = payload.get("aliases", [])
    if not isinstance(aliases, list) or len(aliases) > 20 or any(
        not isinstance(a, str) or not a.strip() or len(a) > 300 for a in aliases
    ):
        raise ValueError("aliases must contain at most 20 nonempty questions")
    item["aliases"] = [a.strip() for a in aliases]
    if not all(normalized_question(q) for q in [item["question"], *item["aliases"]]):
        raise ValueError("questions must contain words")
    approved = payload.get("approved", False)
    if not isinstance(approved, bool):
        raise ValueError("approved must be a boolean")
    item["approved"] = approved
    url = payload.get("source_url", "")
    if not isinstance(url, str) or len(url) > 1000 or any(c.isspace() for c in url):
        raise ValueError("source_url must be an HTTPS URL or empty")
    if url:
        parsed = urlsplit(url)
        if parsed.scheme != "https" or not parsed.hostname or parsed.username or parsed.password:
            raise ValueError("source_url must be HTTPS without credentials")
    item["source_url"] = url
    return item


def find_reviewed_answer(text, items):
    question = normalized_question(text)
    matches = [item for item in items if item["approved"] and question in {
        normalized_question(q) for q in [item["question"], *item["aliases"]]
    }]
    # Conflicting entries need review instead of arbitrary policy selection.
    if len(matches) != 1:
        return None
    item = matches[0]
    english = bool(re.search(r'[A-Za-z]', text)) and not re.search(r'[\u0600-\u06ff]', text)
    source = "Source" if english else "المصدر"
    reply = f"{item['answer']}\n\n{source}: {item['source_title']}"
    if item["source_url"]:
        reply += f"\n{item['source_url']}"
    return reply


DEMO_FAQS = [
    {"question": "شو سياسة الضمان؟", "aliases": ["في ضمان؟", "شو الضمان؟"],
     "answer": "في هذا المثال فقط: ضمان تجريبي لمدة سنة ضد عيوب التصنيع.",
     "source_title": "سياسة المتجر التجريبي — بيانات وهمية", "source_url": "", "approved": True},
    {"question": "What is the warranty?", "aliases": ["Is there a warranty?"],
     "answer": "This example uses a fictional one-year warranty for manufacturing defects.",
     "source_title": "Demo store policy — fictional data", "source_url": "", "approved": True},
]


class SupportStore:
    def __init__(self, connect, sql, postgres):
        self.connect, self.sql, self.postgres = connect, sql, postgres

    @staticmethod
    def now():
        return datetime.now(timezone.utc).isoformat(timespec="seconds")

    @staticmethod
    def rows(cursor):
        names = [column[0] for column in cursor.description]
        return [dict(zip(names, row)) for row in cursor.fetchall()]

    def init_schema(self, conn):
        identity = ("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
                    if self.postgres() else "INTEGER PRIMARY KEY AUTOINCREMENT")
        conn.execute(f"""CREATE TABLE IF NOT EXISTS support_faqs(
            id {identity}, question TEXT NOT NULL, answer TEXT NOT NULL,
            aliases_json TEXT NOT NULL, source_title TEXT NOT NULL,
            source_url TEXT NOT NULL, approved INTEGER NOT NULL DEFAULT 0,
            updated_at TEXT NOT NULL)""")
        conn.execute(f"""CREATE TABLE IF NOT EXISTS support_tickets(
            id {identity}, conversation_id TEXT NOT NULL, channel TEXT NOT NULL,
            open_key TEXT UNIQUE, status TEXT NOT NULL DEFAULT 'open',
            context_json TEXT NOT NULL, messages_json TEXT NOT NULL,
            created_at TEXT NOT NULL, updated_at TEXT NOT NULL)""")
        conn.execute("""CREATE TABLE IF NOT EXISTS support_daily_counts(
            day TEXT NOT NULL, kind TEXT NOT NULL, channel TEXT NOT NULL,
            total INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(day, kind, channel))""")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON support_tickets(status,id)")

    def faqs(self, approved_only=False):
        with closing(self.connect()) as conn:
            where = "WHERE approved = 1" if approved_only else ""
            items = self.rows(conn.execute(
                f"SELECT * FROM support_faqs {where} ORDER BY id LIMIT 200"
            ))
        for item in items:
            item["aliases"] = json.loads(item.pop("aliases_json"))
            item["approved"] = bool(item["approved"])
        return items

    def save_faq(self, payload, faq_id=None):
        item = validated_faq(payload)
        values = (item["question"], item["answer"], json.dumps(item["aliases"], ensure_ascii=False),
                  item["source_title"], item["source_url"], int(item["approved"]), self.now())
        with closing(self.connect()) as conn:
            if faq_id is None:
                if conn.execute("SELECT COUNT(*) FROM support_faqs").fetchone()[0] >= 200:
                    raise ValueError("maximum of 200 FAQ entries reached")
                row = conn.execute(self.sql("""INSERT INTO support_faqs(
                    question,answer,aliases_json,source_title,source_url,approved,updated_at)
                    VALUES(?,?,?,?,?,?,?) RETURNING id"""), values).fetchone()
            else:
                row = conn.execute(self.sql("""UPDATE support_faqs SET question=?,answer=?,
                    aliases_json=?,source_title=?,source_url=?,approved=?,updated_at=?
                    WHERE id=? RETURNING id"""), (*values, faq_id)).fetchone()
            conn.commit()
        return row[0] if row else None

    def delete_faq(self, faq_id):
        with closing(self.connect()) as conn:
            row = conn.execute(self.sql("DELETE FROM support_faqs WHERE id=? RETURNING id"),
                               (faq_id,)).fetchone()
            conn.commit()
        return bool(row)

    def count(self, kind, channel):
        if channel == "demo":
            return
        if kind not in {"faq_answers", "unknown_questions", "handoffs"}:
            raise ValueError("unknown metric")
        with closing(self.connect()) as conn:
            conn.execute(self.sql("""INSERT INTO support_daily_counts(day,kind,channel,total)
                VALUES(?,?,?,1) ON CONFLICT(day,kind,channel)
                DO UPDATE SET total=support_daily_counts.total+1"""),
                (self.now()[:10], kind, str(channel)))
            conn.commit()

    def open_ticket(self, conversation_id, channel, text, state):
        context = {k: state.get(k) for k in ("name", "phone", "city", "product", "qty", "order_id")}
        now = self.now()
        with closing(self.connect()) as conn:
            row = conn.execute(self.sql("""INSERT INTO support_tickets(
                conversation_id,channel,open_key,context_json,messages_json,created_at,updated_at)
                VALUES(?,?,?,?,?,?,?) ON CONFLICT(open_key) DO NOTHING RETURNING id"""),
                (str(conversation_id), str(channel), str(conversation_id),
                 json.dumps(context, ensure_ascii=False),
                 json.dumps([{"text": text[:2000], "at": now}], ensure_ascii=False), now, now)).fetchone()
            created = row is not None
            if not row:
                row = conn.execute(self.sql("SELECT id FROM support_tickets WHERE open_key=?"),
                                   (str(conversation_id),)).fetchone()
            conn.commit()
        if created:
            self.count("handoffs", channel)
        return row[0]

    def ticket(self, ticket_id):
        with closing(self.connect()) as conn:
            items = self.rows(conn.execute(self.sql("SELECT * FROM support_tickets WHERE id=?"),
                                           (ticket_id,)))
        if not items:
            return None
        item = items[0]
        item["context"] = json.loads(item.pop("context_json"))
        item["messages"] = json.loads(item.pop("messages_json"))
        item.pop("open_key")
        return item

    def tickets(self, status="open"):
        if status not in {"open", "closed"}:
            raise ValueError("status must be open or closed")
        with closing(self.connect()) as conn:
            items = self.rows(conn.execute(self.sql("SELECT * FROM support_tickets WHERE status=? ORDER BY id DESC LIMIT 100"),
                                           (status,)))
        for item in items:
            item["context"] = json.loads(item.pop("context_json"))
            item["messages"] = json.loads(item.pop("messages_json"))
            item.pop("open_key")
        return items

    def append_message(self, ticket_id, text):
        with closing(self.connect()) as conn:
            lock = " FOR UPDATE" if self.postgres() else ""
            if not self.postgres():
                conn.execute("BEGIN IMMEDIATE")
            row = conn.execute(self.sql("SELECT messages_json FROM support_tickets WHERE id=? AND status='open'" + lock),
                               (ticket_id,)).fetchone()
            if row:
                messages = json.loads(row[0])
                messages.append({"text": text[:2000], "at": self.now()})
                conn.execute(self.sql("UPDATE support_tickets SET messages_json=?,updated_at=? WHERE id=?"),
                             (json.dumps(messages[-20:], ensure_ascii=False), self.now(), ticket_id))
            conn.commit()

    def close_ticket(self, ticket_id):
        with closing(self.connect()) as conn:
            row = conn.execute(self.sql("""UPDATE support_tickets SET status='closed',open_key=NULL,
                updated_at=? WHERE id=? RETURNING id"""), (self.now(), ticket_id)).fetchone()
            conn.commit()
        return bool(row)

    def metrics(self):
        with closing(self.connect()) as conn:
            counts = dict(conn.execute("SELECT kind,SUM(total) FROM support_daily_counts GROUP BY kind").fetchall())
            open_tickets = conn.execute("SELECT COUNT(*) FROM support_tickets WHERE status='open'").fetchone()[0]
            approved_faqs = conn.execute("SELECT COUNT(*) FROM support_faqs WHERE approved=1").fetchone()[0]
        return {"faq_answers": counts.get("faq_answers", 0),
                "unknown_questions": counts.get("unknown_questions", 0),
                "handoffs": counts.get("handoffs", 0), "open_tickets": open_tickets,
                "approved_faqs": approved_faqs,
                "measurement": "message counts; not verified customer resolutions"}
